all: macos

macos:
	gcc pl_mpeg_player.c -framework SDL2 -framework opengl -framework SDL2_mixer

linux:
	gcc pl_mpeg_player.c -L/usr/local/lib -lSDL2 -lGLEW -lGL
	# I had to copy the glew library files from /usr/local/lib64 to /usr/local/lib to run






 



